---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: enforce-dlp-zone-read
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchBinaries:
            - operator: "In"
              values:
                - "/usr/bin/base64"
                - "/usr/bin/tar"
                - "/usr/bin/gzip"
          matchArgs:
            - index: 0
              operator: "Prefix"
              values:
                - "/tmp/dlp-sensitive"
          matchActions:
            - action: Sigkill
